import { Account } from './types'

export const accounts: Account[] = [
  {
    id: 'meridian-mfg',
    name: 'Meridian Manufacturing',
    industry: 'Manufacturing',
    arr: 360000,
    health: 'red',
    riskScore: 78,
    sentimentScore: 38,
    dataHealthScore: 52,
    profileCompleteness: 35,
    priority: 'P0',
    renewalMonths: 5,
    keySignals: ['Commvault: 11 silent backup failures', 'Nutanix at 92% capacity', 'QBR in 2 weeks', 'Renewal in 5 months'],
    notes: 'Quiet Risk account. Backups have been silently failing for 11 days — client unaware. Infrastructure at critical capacity. If they lose data before we flag this, the relationship is over.',
    valueSnapshot: {
      technicalSignal: 'Commvault shows 11 failed backup jobs over 11 days — 0% success rate on critical manufacturing data sets. Nutanix cluster at 92% capacity. NorthstarMS uptime alerts have fired 3 times this week with no response from client.',
      businessOutcome: 'Undetected backup failure on manufacturing ops data = business continuity liability. A single ransomware event or hardware failure during this window means complete data loss. Proactive disclosure now converts a churn trigger into a trust moment.',
      outcomeCategory: 'Risk Mitigation',
      dollarValue: '$360K ARR + liability at risk',
      sources: ['Commvault', 'Nutanix', 'NorthstarMS'],
      confidence: 'high',
    },
    redFlagSignal: {
      type: 'silent',
      description: 'Backup failures going unreported. Client IT team has not escalated. NorthstarMS monitoring catching what the client is missing.',
      daysSinceContact: 14,
      lastTone: 'neutral',
    },
    backupHealth: {
      provider: 'Commvault',
      successRate: 0,
      failedJobs: 11,
      lastSuccessDate: 'Mar 3, 2026',
      status: 'failed',
      quietRisk: true,
      insight: 'Full backup failure for 11 consecutive days on manufacturing ERP data. Client IT has not escalated — they are not monitoring job-level Commvault logs. This is a Quiet Risk that must be disclosed before the QBR.',
    },
    infraCapacity: {
      provider: 'Nutanix',
      utilizationPct: 92,
      nodeCount: 4,
      status: 'critical',
      expansionTrigger: true,
      estimatedExpansionValue: 65000,
      insight: 'At 92% Nutanix utilization, a single workload spike will trigger performance degradation across all VMs. Node expansion is urgent — lead time is 4–6 weeks from order. Draft the expansion SOW before the QBR.',
    },
    blockerMatch: {
      blocker: 'Silent Commvault failure detected — client unaware — need proactive disclosure strategy.',
      solution: 'WTG Boston pod handled identical Commvault silent failure by framing disclosure as "NorthstarMS proactive catch" — sent a 1-page incident brief before the client noticed, converted near-churn into a 3-year renewal.',
      resolvedBy: 'WTG Boston Pod — Jan 2026',
      matchConfidence: 94,
    },
  },
  {
    id: 'thornfield-fin',
    name: 'Thornfield Financial',
    industry: 'Financial Services',
    arr: 288000,
    health: 'red',
    riskScore: 84,
    sentimentScore: 21,
    dataHealthScore: 55,
    profileCompleteness: 40,
    priority: 'P0',
    keySignals: ['CrowdStrike: 47 threats last 30d (3x surge)', 'Zscaler score dropped to 42', 'Sentiment fell from 68 to 21', 'No QBR in 60 days'],
    notes: 'Security Red Zone. Threat detections tripled while sentiment collapsed. Client is likely aware of the security spike and frustrated we haven\'t proactively engaged.',
    valueSnapshot: {
      technicalSignal: 'CrowdStrike: 47 threat detections in last 30 days — 3x increase vs prior period. Zscaler secure web gateway score dropped from 81 to 42. M365 email analysis shows increasing urgency in client communications over the last 3 weeks.',
      businessOutcome: 'Security Red Zone: elevated threat environment with declining confidence. For a financial services client, a breach during this window carries regulatory exposure (SOC 2, FINRA) and reputational damage beyond the direct cost. Proactive vCISO engagement required within 48 hours.',
      outcomeCategory: 'Risk Mitigation',
      dollarValue: '$288K ARR + compliance exposure',
      sources: ['CrowdStrike', 'Zscaler', 'M365'],
      confidence: 'high',
    },
    redFlagSignal: {
      type: 'critical',
      description: 'Security threats tripled. Sentiment collapsed from 68 to 21. No proactive outreach from WTG in 60 days. Client is in the Red Zone.',
      daysSinceContact: 18,
      lastTone: 'frustrated',
    },
    securityPosture: {
      threatDetections: 47,
      zscalerScore: 42,
      posture: 'critical',
      redZone: true,
      insight: 'Threat detections are at a 3-month high while Zscaler score has dropped 39 points. This combination — elevated threats + low secure access score — is the profile of an account heading toward a breach incident. vCISO emergency briefing should be scheduled within 48 hours.',
    },
    blockerMatch: {
      blocker: 'Security Red Zone triggered — threats up 3x, sentiment collapsed, client disengaged.',
      solution: 'WTG Chicago pod resolved identical Red Zone by scheduling an emergency vCISO briefing within 24 hours, presenting a 3-slide "Threat Intelligence Summary" using CrowdStrike data. Client re-engaged and signed a 12-month security retainer.',
      resolvedBy: 'WTG Chicago Pod — Oct 2025',
      matchConfidence: 91,
    },
  },
  {
    id: 'crestwood-legal',
    name: 'Crestwood Legal Partners',
    industry: 'Legal',
    arr: 240000,
    health: 'yellow',
    riskScore: 54,
    sentimentScore: 48,
    dataHealthScore: 44,
    profileCompleteness: 38,
    priority: 'P1',
    renewalMonths: 4,
    keySignals: ['Commvault: 3 incremental failures (silent)', 'Renewal in 4 months', 'No NorthstarMS review in 90 days', 'M365 Copilot expansion signal'],
    notes: 'Quiet Risk building. 3 incremental backup failures in 7 days — client unaware. Renewal in 4 months. Legal firms carry high liability if client data is lost. Need to disclose and convert into a value conversation before renewal.',
    valueSnapshot: {
      technicalSignal: 'Commvault: 3 incremental backup failures for matter management data in the last 7 days. Success rate at 84%. M365 Teams activity shows lawyer headcount conversations referencing "AI tools" in 4 recent threads.',
      businessOutcome: 'Incremental backup failures on legal matter data carry attorney-client privilege risk. A data loss event before renewal destroys the relationship. Disclosing proactively + presenting M365 Copilot as a billable efficiency tool turns a liability into a $60–90K expansion conversation.',
      outcomeCategory: 'Risk Mitigation',
      dollarValue: '$60–90K expansion + renewal at risk',
      sources: ['Commvault', 'M365', 'NorthstarMS'],
      confidence: 'moderate',
    },
    backupHealth: {
      provider: 'Commvault',
      successRate: 84,
      failedJobs: 3,
      lastSuccessDate: 'Mar 12, 2026',
      status: 'warning',
      quietRisk: true,
      insight: '3 incremental backup failures on legal matter management data. Client has not flagged this — they rely on WTG NorthstarMS to catch it. Disclosure before renewal strengthens the "trusted advisor" position. Delay risks a data event that ends the relationship.',
    },
    expansionPotential: { low: 60000, high: 90000 },
    scopeDrift: {
      description: 'M365 Teams thread from senior partner requesting AI document review capability. Outside current MSA scope — would require M365 Copilot licensing and configuration.',
      sowReference: 'MSA Section 2.1 — Standard M365 Business Premium only',
      source: 'M365 Teams · Mar 8',
      flaggedDaysAgo: 6,
    },
  },
  {
    id: 'apex-health',
    name: 'Apex Healthcare Group',
    industry: 'Healthcare',
    arr: 336000,
    health: 'yellow',
    riskScore: 56,
    sentimentScore: 44,
    dataHealthScore: 60,
    profileCompleteness: 50,
    priority: 'P1',
    keySignals: ['Zscaler score declining', 'CrowdStrike alerts elevated', 'Scope drift on M365', 'No vCISO review in 45 days'],
    notes: 'Security posture weakening in a HIPAA environment. Any breach carries regulatory consequence. vCISO review overdue.',
    valueSnapshot: {
      technicalSignal: 'CrowdStrike: 18 threat detections last 30 days (up from 6). Zscaler score at 61 — below WTG healthcare benchmark of 75. M365 email references new telemedicine platform with 3rd-party API integrations outside current security scope.',
      businessOutcome: 'Elevated threat activity in a HIPAA environment without a current vCISO review creates regulatory exposure. Breach notification costs average $2.1M for healthcare providers under 500 employees (Forrester). vCISO engagement + security retainer upsell is the correct move before the next HIPAA audit cycle.',
      outcomeCategory: 'Compliance',
      dollarValue: '$2.1M breach cost exposure',
      sources: ['CrowdStrike', 'Zscaler', 'M365', 'Forrester'],
      confidence: 'moderate',
    },
    securityPosture: {
      threatDetections: 18,
      zscalerScore: 61,
      posture: 'elevated',
      redZone: false,
      insight: 'Threat detections tripled in 30 days. Zscaler score of 61 is below WTG\'s recommended healthcare baseline of 75. Not yet Red Zone, but trajectory is concerning. vCISO review should be scheduled within 2 weeks before it reaches critical.',
    },
    scopeDrift: {
      description: 'Email from IT director requesting Zscaler policy updates to allow new telemedicine platform API calls. Outside current managed security scope — requires SOW amendment.',
      sowReference: 'MSA Section 3.3 — Standard Zscaler policy management only',
      source: 'M365 Email · Mar 6',
      flaggedDaysAgo: 8,
    },
  },
  {
    id: 'summit-pro',
    name: 'Summit Professional Services',
    industry: 'Professional Services',
    arr: 216000,
    health: 'yellow',
    riskScore: 32,
    sentimentScore: 59,
    dataHealthScore: 68,
    profileCompleteness: 55,
    priority: 'P2',
    keySignals: ['Single point of contact', 'Nutanix at 78%', 'NorthstarMS scores solid', 'No expansion conversation'],
    notes: 'Stable but passive. Single contact is a relationship risk. Nutanix approaching the range where a proactive capacity conversation is warranted.',
    valueSnapshot: {
      technicalSignal: 'NorthstarMS: 99.4% uptime over 90 days. Commvault: 98% backup success rate. Nutanix utilization at 78% — approaching WTG\'s 80% recommendation threshold. No incidents in 120 days.',
      businessOutcome: 'Excellent delivery baseline — zero incidents and near-perfect backup health. Opportunity to convert this stability into a proactive capacity conversation before utilization reaches 85% and becomes a reactive emergency.',
      outcomeCategory: 'Operational',
      dollarValue: '$30–45K proactive capacity SOW',
      sources: ['NorthstarMS', 'Commvault', 'Nutanix'],
      confidence: 'high',
    },
    backupHealth: {
      provider: 'Commvault',
      successRate: 98,
      failedJobs: 1,
      lastSuccessDate: 'Mar 14, 2026',
      status: 'healthy',
      quietRisk: false,
      insight: 'Backup health is strong. 1 minor failure in 30 days — within acceptable range. No action required beyond standard monitoring.',
    },
    infraCapacity: {
      provider: 'Nutanix',
      utilizationPct: 78,
      nodeCount: 3,
      status: 'warning',
      expansionTrigger: false,
      estimatedExpansionValue: 38000,
      insight: 'Nutanix at 78% — approaching WTG\'s 80% proactive threshold. If organic growth continues at current rate, capacity will hit 85% in approximately 60 days. Proactive conversation now avoids an emergency procurement conversation later.',
    },
  },
  {
    id: 'harbor-logistics',
    name: 'Harbor Logistics',
    industry: 'Logistics',
    arr: 192000,
    health: 'green',
    riskScore: 28,
    sentimentScore: 66,
    dataHealthScore: 74,
    profileCompleteness: 65,
    priority: 'expand',
    keySignals: ['Nutanix at 88% — expansion trigger hit', 'Strong relationship', 'Quarterly reviews consistent', 'Lead time risk if delayed'],
    notes: 'Expansion trigger fired. Nutanix at 88% — over WTG threshold. Positive relationship makes this a natural expansion conversation. Every week of delay is a week closer to a performance incident.',
    valueSnapshot: {
      technicalSignal: 'Nutanix cluster hit 88% utilization this week — WTG\'s expansion threshold is 85%. NorthstarMS capacity alert fired on Mar 11. Commvault backups healthy at 97% success. Client sentiment in M365 email consistently positive.',
      businessOutcome: 'Expansion trigger is live. At 88% Nutanix utilization, Harbor is 3–4 weeks from degraded VM performance impacting logistics operations. A proactive node expansion SOW — drafted now — prevents an incident and positions WTG as the firm that anticipated the need, not reacted to it.',
      outcomeCategory: 'Revenue Impact',
      dollarValue: '$55–75K node expansion SOW',
      sources: ['Nutanix', 'NorthstarMS', 'Commvault'],
      confidence: 'high',
    },
    infraCapacity: {
      provider: 'Nutanix',
      utilizationPct: 88,
      nodeCount: 4,
      status: 'critical',
      expansionTrigger: true,
      estimatedExpansionValue: 65000,
      insight: 'Expansion threshold exceeded. At 88% utilization, Nutanix node procurement should begin immediately — standard lead time is 4–6 weeks. Draft the expansion SOW this week. Client relationship is strong and they will expect us to flag this.',
    },
    expansionPotential: { low: 55000, high: 75000 },
    backupHealth: {
      provider: 'Commvault',
      successRate: 97,
      failedJobs: 1,
      lastSuccessDate: 'Mar 14, 2026',
      status: 'healthy',
      quietRisk: false,
      insight: 'Backup health excellent. 1 minor failure in 30 days — normal variance. No action required.',
    },
  },
  {
    id: 'clearwater-tech',
    name: 'Clearwater Technology',
    industry: 'Technology',
    arr: 264000,
    health: 'green',
    riskScore: 18,
    sentimentScore: 78,
    dataHealthScore: 82,
    profileCompleteness: 80,
    priority: 'expand',
    renewalMonths: 9,
    keySignals: ['Best NorthstarMS scores in portfolio', 'M365 Copilot adoption signal', 'Strong vCIO relationship', 'Renewal in 9 months'],
    notes: 'Healthiest account. Strong NorthstarMS scores and an active vCIO relationship. M365 Copilot is the logical expansion vehicle — they are asking about AI tools in Teams.',
    valueSnapshot: {
      technicalSignal: 'NorthstarMS: 99.9% uptime. Commvault: 100% backup success for 60 days. CrowdStrike: 2 low-severity detections, Zscaler score 89. M365 Teams: CTO referenced "AI productivity tools" in 3 separate threads this month.',
      businessOutcome: 'Highest NorthstarMS performance in portfolio. Strong vCIO relationship + active AI interest signal = a natural M365 Copilot expansion conversation. Estimated $90–140K ARR uplift from Copilot licensing and deployment for 60+ users.',
      outcomeCategory: 'Revenue Impact',
      dollarValue: '$90–140K Copilot expansion',
      sources: ['NorthstarMS', 'Commvault', 'CrowdStrike', 'M365'],
      confidence: 'high',
    },
    backupHealth: {
      provider: 'Commvault',
      successRate: 100,
      failedJobs: 0,
      lastSuccessDate: 'Mar 14, 2026',
      status: 'healthy',
      quietRisk: false,
      insight: 'Perfect backup health for 60 consecutive days. Use this as a proof point in the next QBR — data protection is fully covered, enabling the conversation to shift to strategic growth.',
    },
    securityPosture: {
      threatDetections: 2,
      zscalerScore: 89,
      posture: 'secure',
      redZone: false,
      insight: 'Best security posture in the portfolio. Zscaler score of 89 and minimal threat activity. Excellent material for a vCISO value story at renewal.',
    },
    expansionPotential: { low: 90000, high: 140000 },
  },
  {
    id: 'pinnacle-edu',
    name: 'Pinnacle Education Trust',
    industry: 'Education',
    arr: 168000,
    health: 'green',
    riskScore: 25,
    sentimentScore: 64,
    dataHealthScore: 71,
    profileCompleteness: 62,
    priority: 'maintain',
    renewalMonths: 11,
    keySignals: ['Stable NorthstarMS scores', 'Budget-constrained sector', 'Single stakeholder', 'Annual renewal rhythm'],
    notes: 'Steady account. Education budgets limit expansion but relationship is solid. Focus on renewal preparation and profile completion.',
    valueSnapshot: {
      technicalSignal: 'NorthstarMS: 99.1% uptime. Commvault: 95% backup success. Nutanix at 64% utilization. No P1 incidents in 180 days. Single IT director is the primary contact — no secondary relationship mapped.',
      businessOutcome: 'Stable delivery with strong uptime and backup performance. Education sector budget constraints limit near-term expansion, but the 11-month renewal is an opportunity to deepen the relationship and lock in a multi-year agreement.',
      outcomeCategory: 'Operational',
      dollarValue: '$168K renewal at 11 months',
      sources: ['NorthstarMS', 'Commvault', 'Nutanix'],
      confidence: 'high',
    },
    backupHealth: {
      provider: 'Commvault',
      successRate: 95,
      failedJobs: 2,
      lastSuccessDate: 'Mar 13, 2026',
      status: 'healthy',
      quietRisk: false,
      insight: '2 minor failures in 30 days — within acceptable range for this environment. No action required. Good material for the next check-in to demonstrate NorthstarMS monitoring value.',
    },
    infraCapacity: {
      provider: 'Nutanix',
      utilizationPct: 64,
      nodeCount: 2,
      status: 'healthy',
      expansionTrigger: false,
      insight: 'Comfortable at 64%. No expansion needed in the near term. Steady-state monitoring is appropriate.',
    },
  },
]

export const portfolioStats = {
  totalArr: 2064000,
  totalAccounts: 8,
  p0Arr: 648000,
  p1Arr: 576000,
  stableArr: 840000,
  expansionLow: 145000,
  expansionHigh: 215000,
  nearTermExpansionLow: 55000,
  nearTermExpansionHigh: 75000,
}
